#ifndef __PTVIEWER_H__
#define __PTVIEWER_H__

#ifdef __KERNEL__
#include <devioctl.h>
#else
#include <winioctl.h>
#endif


// IoControl
#define IOCTL_GET_VT_ROUND_TRIP CTL_CODE(FILE_DEVICE_UNKNOWN, 11, METHOD_BUFFERED, FILE_ANY_ACCESS)
// input : KAFFINITY, output TlbInfo
#define IOCTL_GET_INSTRUCTION_TLB_INFO CTL_CODE(FILE_DEVICE_UNKNOWN, 21, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_GET_DATA_TLB_INFO  CTL_CODE(FILE_DEVICE_UNKNOWN, 22, METHOD_BUFFERED, FILE_ANY_ACCESS)
// set target cr3
#define IOCTL_SET_TARGET  CTL_CODE(FILE_DEVICE_UNKNOWN, 31, METHOD_NEITHER, FILE_ANY_ACCESS)

#define IOCTL_READ_CR3 CTL_CODE(FILE_DEVICE_UNKNOWN, 41, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_GET_PHYSICAL_ADDRESS CTL_CODE(FILE_DEVICE_UNKNOWN, 44, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_COPY_PHYSICAL_MEMORY CTL_CODE(FILE_DEVICE_UNKNOWN, 46, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_COPY_MEMORY CTL_CODE(FILE_DEVICE_UNKNOWN, 48, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_READ_CR0 CTL_CODE(FILE_DEVICE_UNKNOWN, 51, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_READ_CR2 CTL_CODE(FILE_DEVICE_UNKNOWN, 52, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_READ_CR4 CTL_CODE(FILE_DEVICE_UNKNOWN, 54, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_WRITE_CR0 CTL_CODE(FILE_DEVICE_UNKNOWN, 56, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_WRITE_CR3 CTL_CODE(FILE_DEVICE_UNKNOWN, 58, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_WRITE_CR4 CTL_CODE(FILE_DEVICE_UNKNOWN, 59, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_READ_MSR CTL_CODE(FILE_DEVICE_UNKNOWN, 61, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_WRITE_MSR CTL_CODE(FILE_DEVICE_UNKNOWN, 62, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_DO_WBINVD CTL_CODE(FILE_DEVICE_UNKNOWN, 66, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DO_INVLPG CTL_CODE(FILE_DEVICE_UNKNOWN, 67, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_CHECK_ACCESS_LATENCY CTL_CODE(FILE_DEVICE_UNKNOWN, 81, METHOD_BUFFERED, FILE_ANY_ACCESS)

#endif /* __PTVIEWER_H__ */
